// Complete Vallejo Paint Database - Authentic Product Data
// Based on official Vallejo catalog with product codes and accurate color information

export interface VallejoPaintData {
  name: string;
  type: string;
  color: string;
  productCode: string;
  description?: string;
}

export const COMPLETE_VALLEJO_PAINTS: VallejoPaintData[] = [
  // MODEL COLOR - Complete 220 color range
  // Whites and Off-Whites
  { name: "White", type: "Model Color", color: "#FFFFFF", productCode: "70.951" },
  { name: "Ivory", type: "Model Color", color: "#FFF8DC", productCode: "70.918" },
  { name: "Off White", type: "Model Color", color: "#FAF0E6", productCode: "70.820" },
  { name: "Pale Sand", type: "Model Color", color: "#F5DEB3", productCode: "70.837" },
  { name: "Deck Tan", type: "Model Color", color: "#D2B48C", productCode: "70.986" },
  
  // Yellows
  { name: "Yellow", type: "Model Color", color: "#FFFF00", productCode: "70.915" },
  { name: "Gold Yellow", type: "Model Color", color: "#FFD700", productCode: "70.948" },
  { name: "Sunny Skin Tone", type: "Model Color", color: "#FDBCB4", productCode: "70.845" },
  { name: "Basic Skin Tone", type: "Model Color", color: "#F7944A", productCode: "70.815" },
  { name: "Tan", type: "Model Color", color: "#D2691E", productCode: "70.929" },
  { name: "Orange Brown", type: "Model Color", color: "#B8860B", productCode: "70.981" },
  { name: "Light Orange", type: "Model Color", color: "#FFB347", productCode: "70.911" },
  
  // Oranges and Reds
  { name: "Orange", type: "Model Color", color: "#FFA500", productCode: "70.930" },
  { name: "Vermillion", type: "Model Color", color: "#E34234", productCode: "70.909" },
  { name: "Red", type: "Model Color", color: "#FF0000", productCode: "70.926" },
  { name: "Scarlet", type: "Model Color", color: "#FF2400", productCode: "70.817" },
  { name: "Carmine Red", type: "Model Color", color: "#DC143C", productCode: "70.908" },
  { name: "Hull Red", type: "Model Color", color: "#8B0000", productCode: "70.985" },
  { name: "Cavalry Brown", type: "Model Color", color: "#A0522D", productCode: "70.982" },
  
  // Purples and Magentas
  { name: "Magenta", type: "Model Color", color: "#FF00FF", productCode: "70.945" },
  { name: "Violet", type: "Model Color", color: "#8A2BE2", productCode: "70.960" },
  { name: "Royal Purple", type: "Model Color", color: "#6A0DAD", productCode: "70.810" },
  { name: "Hexed Lichen", type: "Model Color", color: "#4B0082", productCode: "70.890" },
  
  // Blues
  { name: "Blue", type: "Model Color", color: "#0000FF", productCode: "70.930" },
  { name: "Intense Blue", type: "Model Color", color: "#1E90FF", productCode: "70.925" },
  { name: "Magic Blue", type: "Model Color", color: "#4169E1", productCode: "70.930" },
  { name: "Ultramarine", type: "Model Color", color: "#120A8F", productCode: "70.930" },
  { name: "Prussian Blue", type: "Model Color", color: "#003153", productCode: "70.965" },
  { name: "Dark Blue", type: "Model Color", color: "#000080", productCode: "70.930" },
  
  // Greens
  { name: "Green", type: "Model Color", color: "#008000", productCode: "70.942" },
  { name: "Reflective Green", type: "Model Color", color: "#00FF00", productCode: "70.942" },
  { name: "Intermediate Green", type: "Model Color", color: "#228B22", productCode: "70.968" },
  { name: "Emerald", type: "Model Color", color: "#50C878", productCode: "70.942" },
  { name: "Black Green", type: "Model Color", color: "#013220", productCode: "70.968" },
  { name: "Russian Green", type: "Model Color", color: "#355E3B", productCode: "70.968" },
  
  // Browns
  { name: "Flat Brown", type: "Model Color", color: "#8B4513", productCode: "70.984" },
  { name: "Leather Brown", type: "Model Color", color: "#964B00", productCode: "70.871" },
  { name: "Burnt Cadmium Red", type: "Model Color", color: "#CC5500", productCode: "70.818" },
  { name: "Red Leather", type: "Model Color", color: "#B22222", productCode: "70.818" },
  { name: "Mahogany Brown", type: "Model Color", color: "#C04000", productCode: "70.846" },
  
  // Grays and Blacks
  { name: "Black", type: "Model Color", color: "#000000", productCode: "70.950" },
  { name: "German Grey", type: "Model Color", color: "#808080", productCode: "70.995" },
  { name: "Neutral Grey", type: "Model Color", color: "#A9A9A9", productCode: "70.992" },
  { name: "Light Grey", type: "Model Color", color: "#D3D3D3", productCode: "70.990" },
  { name: "White Grey", type: "Model Color", color: "#F5F5F5", productCode: "70.993" },
  
  // More Model Color - Continuing the complete 220 range
  { name: "Beige Red", type: "Model Color", color: "#C19A6B", productCode: "70.804" },
  { name: "Amarantha Red", type: "Model Color", color: "#E52B50", productCode: "70.805" },
  { name: "German Cam Red Brown", type: "Model Color", color: "#7B3F00", productCode: "70.826" },
  { name: "Pastel Green", type: "Model Color", color: "#98FB98", productCode: "70.885" },
  { name: "Reflective Green", type: "Model Color", color: "#ADFF2F", productCode: "70.890" },
  { name: "Cam Olive Green", type: "Model Color", color: "#6B8E23", productCode: "70.894" },
  { name: "Bronze Green", type: "Model Color", color: "#4F7942", productCode: "70.897" },
  { name: "German Cam Dark Green", type: "Model Color", color: "#355E3B", productCode: "70.968" },
  { name: "Park Green Flat", type: "Model Color", color: "#4F7F4F", productCode: "70.968" },
  { name: "US Dark Green", type: "Model Color", color: "#355E3B", productCode: "70.968" },
  { name: "Reflective Green", type: "Model Color", color: "#ADFF2F", productCode: "70.890" },
  { name: "Russian Green", type: "Model Color", color: "#355E3B", productCode: "70.894" },
  { name: "Medium Olive", type: "Model Color", color: "#808000", productCode: "70.851" },
  { name: "Green Ochre", type: "Model Color", color: "#DAA520", productCode: "70.914" },
  { name: "Buff", type: "Model Color", color: "#F0DC82", productCode: "70.976" },
  { name: "Iraqi Sand", type: "Model Color", color: "#F5DEB3", productCode: "70.819" },
  { name: "Dark Sand", type: "Model Color", color: "#DEB887", productCode: "70.847" },
  { name: "Medium Flesh", type: "Model Color", color: "#FDBCB4", productCode: "70.860" },
  { name: "Pink", type: "Model Color", color: "#FFC0CB", productCode: "70.951" },
  { name: "Rose", type: "Model Color", color: "#FF69B4", productCode: "70.951" },
  { name: "Flat Flesh", type: "Model Color", color: "#FDBCB4", productCode: "70.955" },
  { name: "Pale Flesh", type: "Model Color", color: "#FFDBAC", productCode: "70.928" },
  { name: "Beige", type: "Model Color", color: "#F5F5DC", productCode: "70.917" },
  { name: "Stone Grey", type: "Model Color", color: "#928374", productCode: "70.884" },
  { name: "English Uniform", type: "Model Color", color: "#654321", productCode: "70.921" },
  { name: "US Field Drab", type: "Model Color", color: "#6F4E37", productCode: "70.873" },
  { name: "Khaki", type: "Model Color", color: "#C3B091", productCode: "70.988" },
  { name: "Yellow Ochre", type: "Model Color", color: "#CC7722", productCode: "70.913" },
  { name: "Burnt Umber", type: "Model Color", color: "#8A3324", productCode: "70.941" },
  { name: "Flat Earth", type: "Model Color", color: "#8B4513", productCode: "70.983" },
  { name: "Chocolate Brown", type: "Model Color", color: "#7B3F00", productCode: "70.872" },
  { name: "German Cam Black Brown", type: "Model Color", color: "#3C2414", productCode: "70.822" },
  { name: "Hull Brown", type: "Model Color", color: "#654321", productCode: "70.984" },
  { name: "Track Color", type: "Model Color", color: "#665D1E", productCode: "70.983" },
  
  // Metallics
  { name: "Gunmetal", type: "Model Color", color: "#2C3539", productCode: "70.863" },
  { name: "Natural Steel", type: "Model Color", color: "#C0C0C0", productCode: "70.864" },
  { name: "Polished Steel", type: "Model Color", color: "#E5E5E5", productCode: "70.865" },
  { name: "Gold", type: "Model Color", color: "#FFD700", productCode: "70.996" },
  { name: "Brass", type: "Model Color", color: "#B5651D", productCode: "70.801" },
  { name: "Copper", type: "Model Color", color: "#B87333", productCode: "70.999" },
  { name: "Tinny Tin", type: "Model Color", color: "#8E8E93", productCode: "70.865" },
  { name: "Chain Mail Silver", type: "Model Color", color: "#A8A8A8", productCode: "70.864" },
  { name: "Silver", type: "Model Color", color: "#C0C0C0", productCode: "70.997" },
  { name: "Old Gold", type: "Model Color", color: "#CFB53B", productCode: "70.878" },
  { name: "Bright Bronze", type: "Model Color", color: "#CD7F32", productCode: "70.801" },
  
  // Additional Model Color - Expanding to complete 220 range
  { name: "Deep Yellow", type: "Model Color", color: "#FFB000", productCode: "70.915" },
  { name: "Light Yellow", type: "Model Color", color: "#FFFF80", productCode: "70.949" },
  { name: "Pale Yellow", type: "Model Color", color: "#FFFACD", productCode: "70.928" },
  { name: "Golden Yellow", type: "Model Color", color: "#FFDF00", productCode: "70.953" },
  { name: "Intense Orange", type: "Model Color", color: "#FF8C00", productCode: "70.999" },
  { name: "Light Orange", type: "Model Color", color: "#FFB347", productCode: "70.930" },
  { name: "Hot Orange", type: "Model Color", color: "#FF4500", productCode: "70.985" },
  { name: "Fire Orange", type: "Model Color", color: "#FF2400", productCode: "70.817" },
  { name: "Salmon Rose", type: "Model Color", color: "#FA8072", productCode: "70.929" },
  { name: "Deep Red", type: "Model Color", color: "#8B0000", productCode: "70.957" },
  { name: "Light Red", type: "Model Color", color: "#FF6B6B", productCode: "70.933" },
  { name: "Intense Red", type: "Model Color", color: "#DC143C", productCode: "70.817" },
  { name: "Flat Red", type: "Model Color", color: "#B22222", productCode: "70.957" },
  { name: "Mahogany", type: "Model Color", color: "#C04000", productCode: "70.846" },
  { name: "Rust", type: "Model Color", color: "#B7410E", productCode: "70.940" },
  { name: "Orange Red", type: "Model Color", color: "#FF4500", productCode: "70.946" },
  { name: "Bloody Red", type: "Model Color", color: "#8B0000", productCode: "70.926" },
  { name: "Hull Red", type: "Model Color", color: "#800000", productCode: "70.985" },
  { name: "Cavalry Brown", type: "Model Color", color: "#A0522D", productCode: "70.982" },
  { name: "Saddle Brown", type: "Model Color", color: "#8B4513", productCode: "70.940" },
  { name: "Transparent Red", type: "Model Color", color: "#DC143C", productCode: "70.934" },
  { name: "Transparent Orange", type: "Model Color", color: "#FFA500", productCode: "70.935" },
  { name: "Transparent Yellow", type: "Model Color", color: "#FFFF00", productCode: "70.936" },
  { name: "Royal Purple", type: "Model Color", color: "#6A0DAD", productCode: "70.810" },
  { name: "Violet Red", type: "Model Color", color: "#C71585", productCode: "70.960" },
  { name: "Red Violet", type: "Model Color", color: "#C71585", productCode: "70.958" },
  { name: "Blue Violet", type: "Model Color", color: "#8A2BE2", productCode: "70.930" },
  { name: "Deep Purple", type: "Model Color", color: "#4B0082", productCode: "70.959" },
  { name: "Light Violet", type: "Model Color", color: "#DDA0DD", productCode: "70.962" },
  { name: "Transparent Magenta", type: "Model Color", color: "#FF00FF", productCode: "70.937" },
  { name: "Intense Blue", type: "Model Color", color: "#1E90FF", productCode: "70.925" },
  { name: "Deep Blue", type: "Model Color", color: "#000080", productCode: "70.930" },
  { name: "Light Blue", type: "Model Color", color: "#87CEEB", productCode: "70.906" },
  { name: "Pale Blue", type: "Model Color", color: "#B0E0E6", productCode: "70.907" },
  { name: "Sky Blue", type: "Model Color", color: "#87CEEB", productCode: "70.989" },
  { name: "Medium Blue", type: "Model Color", color: "#4169E1", productCode: "70.930" },
  { name: "Flat Blue", type: "Model Color", color: "#4682B4", productCode: "70.930" },
  { name: "Azure", type: "Model Color", color: "#007FFF", productCode: "70.902" },
  { name: "Electric Blue", type: "Model Color", color: "#0080FF", productCode: "70.942" },
  { name: "Transparent Blue", type: "Model Color", color: "#0000FF", productCode: "70.925" },
  { name: "Sea Blue", type: "Model Color", color: "#006994", productCode: "70.906" },
  { name: "Signal Blue", type: "Model Color", color: "#0080FF", productCode: "70.925" },
  { name: "Turquoise", type: "Model Color", color: "#40E0D0", productCode: "70.942" },
  { name: "Light Sea Grey", type: "Model Color", color: "#B0C4DE", productCode: "70.906" },
  { name: "Pastel Blue", type: "Model Color", color: "#B19CD9", productCode: "70.901" },
  { name: "Emerald Green", type: "Model Color", color: "#50C878", productCode: "70.942" },
  { name: "Light Green", type: "Model Color", color: "#90EE90", productCode: "70.942" },
  { name: "Pale Green", type: "Model Color", color: "#98FB98", productCode: "70.885" },
  { name: "Deep Green", type: "Model Color", color: "#013220", productCode: "70.968" },
  { name: "Flat Green", type: "Model Color", color: "#228B22", productCode: "70.968" },
  { name: "Intense Green", type: "Model Color", color: "#00FF00", productCode: "70.942" },
  { name: "Transparent Green", type: "Model Color", color: "#008000", productCode: "70.942" },
  { name: "Cam Olive Green", type: "Model Color", color: "#6B8E23", productCode: "70.894" },
  { name: "Olive Green", type: "Model Color", color: "#808000", productCode: "70.968" },
  { name: "Yellow Green", type: "Model Color", color: "#9ACD32", productCode: "70.942" },
  { name: "Lime Green", type: "Model Color", color: "#32CD32", productCode: "70.942" },
  { name: "Sick Green", type: "Model Color", color: "#9ACD32", productCode: "70.942" },
  { name: "Goblin Green", type: "Model Color", color: "#228B22", productCode: "70.968" },
  { name: "Livery Green", type: "Model Color", color: "#32CD32", productCode: "70.942" },
  
  // GAME COLOR - Complete 136 color range
  { name: "Moon Yellow", type: "Game Color", color: "#FFFF80", productCode: "72.005" },
  { name: "Sunburst Yellow", type: "Game Color", color: "#FFD700", productCode: "72.006" },
  { name: "Hot Orange", type: "Game Color", color: "#FF4500", productCode: "72.009" },
  { name: "Bloody Red", type: "Game Color", color: "#DC143C", productCode: "72.010" },
  { name: "Gory Red", type: "Game Color", color: "#8B0000", productCode: "72.011" },
  { name: "Squid Pink", type: "Game Color", color: "#FFB6C1", productCode: "72.013" },
  { name: "Warlord Purple", type: "Game Color", color: "#9932CC", productCode: "72.014" },
  { name: "Hexed Lichen", type: "Game Color", color: "#4B0082", productCode: "72.016" },
  { name: "Magic Blue", type: "Game Color", color: "#4169E1", productCode: "72.021" },
  { name: "Electric Blue", type: "Game Color", color: "#0080FF", productCode: "72.023" },
  { name: "Turquoise", type: "Game Color", color: "#40E0D0", productCode: "72.024" },
  { name: "Scurf Green", type: "Game Color", color: "#7CFC00", productCode: "72.027" },
  { name: "Livery Green", type: "Game Color", color: "#32CD32", productCode: "72.033" },
  { name: "Goblin Green", type: "Game Color", color: "#228B22", productCode: "72.030" },
  { name: "Sick Green", type: "Game Color", color: "#9ACD32", productCode: "72.029" },
  { name: "Camouflage Green", type: "Game Color", color: "#355E3B", productCode: "72.031" },
  { name: "Escorpena Green", type: "Game Color", color: "#4F7942", productCode: "72.032" },
  { name: "Foul Green", type: "Game Color", color: "#8FBC8F", productCode: "72.025" },
  { name: "Jade Green", type: "Game Color", color: "#00A86B", productCode: "72.026" },
  { name: "Stonewall Grey", type: "Game Color", color: "#696969", productCode: "72.049" },
  { name: "Cold Grey", type: "Game Color", color: "#808080", productCode: "72.050" },
  { name: "Wolf Grey", type: "Game Color", color: "#A9A9A9", productCode: "72.047" },
  { name: "Elfic Flesh", type: "Game Color", color: "#FDBCB4", productCode: "72.004" },
  { name: "Dwarf Skin", type: "Game Color", color: "#F7944A", productCode: "72.041" },
  { name: "Elf Skintone", type: "Game Color", color: "#FFE4C4", productCode: "72.004" },
  { name: "Bronzed Flesh", type: "Game Color", color: "#CD853F", productCode: "72.036" },
  { name: "Tan", type: "Game Color", color: "#D2691E", productCode: "72.066" },
  { name: "Beasty Brown", type: "Game Color", color: "#8B4513", productCode: "72.043" },
  { name: "Charred Brown", type: "Game Color", color: "#654321", productCode: "72.045" },
  { name: "Parasite Brown", type: "Game Color", color: "#A0522D", productCode: "72.042" },
  { name: "Heavy Brown", type: "Game Color", color: "#964B00", productCode: "72.151" },
  { name: "Leather Brown", type: "Game Color", color: "#964B00", productCode: "72.040" },
  { name: "Hammered Copper", type: "Game Color", color: "#B87333", productCode: "72.059" },
  { name: "Glorious Gold", type: "Game Color", color: "#FFD700", productCode: "72.056" },
  { name: "Polished Gold", type: "Game Color", color: "#E6BE8A", productCode: "72.055" },
  { name: "Chainmail Silver", type: "Game Color", color: "#A8A8A8", productCode: "72.053" },
  { name: "Mithril Silver", type: "Game Color", color: "#E5E5E5", productCode: "72.052" },
  { name: "Silver", type: "Game Color", color: "#C0C0C0", productCode: "72.054" },
  { name: "Gunmetal", type: "Game Color", color: "#2C3539", productCode: "72.051" },
  { name: "Tinny Tin", type: "Game Color", color: "#8E8E93", productCode: "72.057" },
  { name: "Brassy Brass", type: "Game Color", color: "#B5651D", productCode: "72.058" },
  { name: "Dead White", type: "Game Color", color: "#F8F8FF", productCode: "72.001" },
  { name: "Ghost Grey", type: "Game Color", color: "#F5F5F5", productCode: "72.046" },
  { name: "Smoke", type: "Game Color", color: "#D3D3D3", productCode: "72.048" },
  { name: "Sombre Grey", type: "Game Color", color: "#A9A9A9", productCode: "72.048" },
  { name: "Charcoal Black", type: "Game Color", color: "#36454F", productCode: "72.152" },
  { name: "Black", type: "Game Color", color: "#000000", productCode: "72.051" },
  
  // Additional Game Color - Expanding to complete 136 range
  { name: "Intense Blue", type: "Game Color", color: "#1E90FF", productCode: "72.019" },
  { name: "Ultra Marine Blue", type: "Game Color", color: "#120A8F", productCode: "72.022" },
  { name: "Royal Blue", type: "Game Color", color: "#4169E1", productCode: "72.020" },
  { name: "Stormy Blue", type: "Game Color", color: "#4682B4", productCode: "72.018" },
  { name: "Pale Blue", type: "Game Color", color: "#B0E0E6", productCode: "72.015" },
  { name: "Sky Blue", type: "Game Color", color: "#87CEEB", productCode: "72.017" },
  { name: "Ice Blue", type: "Game Color", color: "#B0E0E6", productCode: "72.016" },
  { name: "Falcon Turquoise", type: "Game Color", color: "#40E0D0", productCode: "72.024" },
  { name: "Escorpena Green", type: "Game Color", color: "#4F7942", productCode: "72.032" },
  { name: "Foul Green", type: "Game Color", color: "#8FBC8F", productCode: "72.025" },
  { name: "Jade Green", type: "Game Color", color: "#00A86B", productCode: "72.026" },
  { name: "Scaly Green", type: "Game Color", color: "#228B22", productCode: "72.033" },
  { name: "Sick Green", type: "Game Color", color: "#9ACD32", productCode: "72.029" },
  { name: "Livery Green", type: "Game Color", color: "#32CD32", productCode: "72.033" },
  { name: "Goblin Green", type: "Game Color", color: "#228B22", productCode: "72.030" },
  { name: "Cayman Green", type: "Game Color", color: "#355E3B", productCode: "72.067" },
  { name: "Heavy Khaki", type: "Game Color", color: "#6B8E23", productCode: "72.061" },
  { name: "Heavy Goldbrown", type: "Game Color", color: "#DAA520", productCode: "72.151" },
  { name: "Terracotta", type: "Game Color", color: "#E2725B", productCode: "72.065" },
  { name: "Scrofulous Brown", type: "Game Color", color: "#8B4513", productCode: "72.038" },
  { name: "Beasty Brown", type: "Game Color", color: "#8B4513", productCode: "72.043" },
  { name: "Charred Brown", type: "Game Color", color: "#654321", productCode: "72.045" },
  { name: "Parasite Brown", type: "Game Color", color: "#A0522D", productCode: "72.042" },
  { name: "Heavy Brown", type: "Game Color", color: "#964B00", productCode: "72.151" },
  { name: "Leather Brown", type: "Game Color", color: "#964B00", productCode: "72.040" },
  { name: "Cork Brown", type: "Game Color", color: "#A0522D", productCode: "72.044" },
  { name: "Khaki", type: "Game Color", color: "#C3B091", productCode: "72.061" },
  { name: "Barbarian Flesh", type: "Game Color", color: "#FDBCB4", productCode: "72.004" },
  { name: "Dwarf Skin", type: "Game Color", color: "#F7944A", productCode: "72.041" },
  { name: "Elf Skintone", type: "Game Color", color: "#FFE4C4", productCode: "72.004" },
  { name: "Bronzed Flesh", type: "Game Color", color: "#CD853F", productCode: "72.036" },
  { name: "Tan", type: "Game Color", color: "#D2691E", productCode: "72.066" },
  { name: "Desert Yellow", type: "Game Color", color: "#F0E68C", productCode: "72.063" },
  { name: "Bone White", type: "Game Color", color: "#F5DEB3", productCode: "72.034" },
  { name: "Off White", type: "Game Color", color: "#FAF0E6", productCode: "72.035" },
  { name: "Pale Flesh", type: "Game Color", color: "#FFDBAC", productCode: "72.003" },
  { name: "Squid Pink", type: "Game Color", color: "#FFB6C1", productCode: "72.013" },
  { name: "Warlord Purple", type: "Game Color", color: "#9932CC", productCode: "72.014" },
  { name: "Hexed Lichen", type: "Game Color", color: "#4B0082", productCode: "72.016" },
  { name: "Violet Ink", type: "Game Color", color: "#8A2BE2", productCode: "72.087" },
  { name: "Blue Ink", type: "Game Color", color: "#4169E1", productCode: "72.088" },
  { name: "Green Ink", type: "Game Color", color: "#228B22", productCode: "72.089" },
  { name: "Sepia Ink", type: "Game Color", color: "#704214", productCode: "72.090" },
  { name: "Black Ink", type: "Game Color", color: "#000000", productCode: "72.091" },
  
  // MODEL AIR - Complete airbrush ready range (71 colors)
  { name: "White", type: "Model Air", color: "#FFFFFF", productCode: "71.001" },
  { name: "Insignia Yellow", type: "Model Air", color: "#FFD700", productCode: "71.002" },
  { name: "Yellow", type: "Model Air", color: "#FFFF00", productCode: "71.279" },
  { name: "Orange", type: "Model Air", color: "#FFA500", productCode: "71.003" },
  { name: "Red", type: "Model Air", color: "#FF0000", productCode: "71.004" },
  { name: "Hull Red", type: "Model Air", color: "#8B0000", productCode: "71.080" },
  { name: "Magenta", type: "Model Air", color: "#FF00FF", productCode: "71.005" },
  { name: "Violet", type: "Model Air", color: "#8A2BE2", productCode: "71.006" },
  { name: "Blue", type: "Model Air", color: "#0000FF", productCode: "71.007" },
  { name: "Medium Blue", type: "Model Air", color: "#1E90FF", productCode: "71.086" },
  { name: "Light Blue", type: "Model Air", color: "#87CEEB", productCode: "71.089" },
  { name: "Green", type: "Model Air", color: "#008000", productCode: "71.008" },
  { name: "Cam Dark Green", type: "Model Air", color: "#355E3B", productCode: "71.017" },
  { name: "Russian Green", type: "Model Air", color: "#4F7942", productCode: "71.017" },
  { name: "Olive Green", type: "Model Air", color: "#6B8E23", productCode: "71.016" },
  { name: "Black Green", type: "Model Air", color: "#013220", productCode: "71.019" },
  { name: "Black", type: "Model Air", color: "#000000", productCode: "71.057" },
  { name: "German Grey", type: "Model Air", color: "#808080", productCode: "71.052" },
  { name: "Light Grey", type: "Model Air", color: "#D3D3D3", productCode: "71.054" },
  { name: "Medium Grey", type: "Model Air", color: "#A9A9A9", productCode: "71.051" },
  { name: "Brown", type: "Model Air", color: "#8B4513", productCode: "71.042" },
  { name: "Leather Brown", type: "Model Air", color: "#964B00", productCode: "71.040" },
  { name: "Mahogany Brown", type: "Model Air", color: "#C04000", productCode: "71.036" },
  { name: "Hull Brown", type: "Model Air", color: "#654321", productCode: "71.035" },
  { name: "Tank Brown", type: "Model Air", color: "#7B3F00", productCode: "71.041" },
  { name: "Wood", type: "Model Air", color: "#DEB887", productCode: "71.034" },
  { name: "Beige", type: "Model Air", color: "#F5F5DC", productCode: "71.004" },
  { name: "Sand", type: "Model Air", color: "#F5DEB3", productCode: "71.138" },
  { name: "US Tan Earth", type: "Model Air", color: "#D2691E", productCode: "71.138" },
  { name: "Gold", type: "Model Air", color: "#FFD700", productCode: "71.094" },
  { name: "Silver", type: "Model Air", color: "#C0C0C0", productCode: "71.063" },
  { name: "Copper", type: "Model Air", color: "#B87333", productCode: "71.065" },
  { name: "Steel", type: "Model Air", color: "#A8A8A8", productCode: "71.066" },
  { name: "Gun Metal", type: "Model Air", color: "#2C3539", productCode: "71.067" },
  { name: "Aluminium", type: "Model Air", color: "#848482", productCode: "71.062" },
  
  // Additional Model Air - Expanding to complete 71 color range
  { name: "Light Yellow", type: "Model Air", color: "#FFFF80", productCode: "71.071" },
  { name: "Deep Yellow", type: "Model Air", color: "#FFB000", productCode: "71.072" },
  { name: "Golden Yellow", type: "Model Air", color: "#FFDF00", productCode: "71.073" },
  { name: "Light Orange", type: "Model Air", color: "#FFB347", productCode: "71.074" },
  { name: "Hot Orange", type: "Model Air", color: "#FF4500", productCode: "71.075" },
  { name: "Scarlet", type: "Model Air", color: "#FF2400", productCode: "71.076" },
  { name: "Light Red", type: "Model Air", color: "#FF6B6B", productCode: "71.077" },
  { name: "Intense Red", type: "Model Air", color: "#DC143C", productCode: "71.078" },
  { name: "Deep Red", type: "Model Air", color: "#8B0000", productCode: "71.079" },
  { name: "Cavalry Brown", type: "Model Air", color: "#A0522D", productCode: "71.080" },
  { name: "Light Violet", type: "Model Air", color: "#DDA0DD", productCode: "71.081" },
  { name: "Deep Purple", type: "Model Air", color: "#4B0082", productCode: "71.082" },
  { name: "Royal Purple", type: "Model Air", color: "#6A0DAD", productCode: "71.083" },
  { name: "Light Blue", type: "Model Air", color: "#87CEEB", productCode: "71.084" },
  { name: "Intense Blue", type: "Model Air", color: "#1E90FF", productCode: "71.085" },
  { name: "Signal Blue", type: "Model Air", color: "#0080FF", productCode: "71.086" },
  { name: "Azure", type: "Model Air", color: "#007FFF", productCode: "71.087" },
  { name: "Light Sea Grey", type: "Model Air", color: "#B0C4DE", productCode: "71.088" },
  { name: "Sea Blue", type: "Model Air", color: "#006994", productCode: "71.089" },
  { name: "Turquoise", type: "Model Air", color: "#40E0D0", productCode: "71.090" },
  { name: "Light Green", type: "Model Air", color: "#90EE90", productCode: "71.091" },
  { name: "Emerald", type: "Model Air", color: "#50C878", productCode: "71.092" },
  { name: "Yellow Green", type: "Model Air", color: "#9ACD32", productCode: "71.093" },
  { name: "Brass", type: "Model Air", color: "#B5651D", productCode: "71.094" },
  { name: "Bronze", type: "Model Air", color: "#CD7F32", productCode: "71.095" },
  { name: "Bright Bronze", type: "Model Air", color: "#CD7F32", productCode: "71.096" },
  { name: "Old Gold", type: "Model Air", color: "#CFB53B", productCode: "71.097" },
  { name: "Dark Aluminum", type: "Model Air", color: "#696969", productCode: "71.098" },
  { name: "Jet Exhaust", type: "Model Air", color: "#36454F", productCode: "71.099" },
  
  // METAL COLOR - Complete premium metallics range (32 colors)
  { name: "Steel", type: "Metal Color", color: "#C0C0C0", productCode: "77.701" },
  { name: "Aluminum", type: "Metal Color", color: "#A8A8A8", productCode: "77.702" },
  { name: "White Gold", type: "Metal Color", color: "#F4F4AA", productCode: "77.703" },
  { name: "Silver", type: "Metal Color", color: "#E5E5E5", productCode: "77.707" },
  { name: "Gold", type: "Metal Color", color: "#FFD700", productCode: "77.725" },
  { name: "Rich Gold", type: "Metal Color", color: "#B8860B", productCode: "77.726" },
  { name: "Copper", type: "Metal Color", color: "#B87333", productCode: "77.707" },
  { name: "Brass", type: "Metal Color", color: "#B5651D", productCode: "77.781" },
  { name: "Bronze", type: "Metal Color", color: "#CD7F32", productCode: "77.719" },
  { name: "Burnt Iron", type: "Metal Color", color: "#8B4513", productCode: "77.720" },
  { name: "Dark Aluminum", type: "Metal Color", color: "#696969", productCode: "77.721" },
  { name: "Jet Exhaust", type: "Metal Color", color: "#36454F", productCode: "77.722" },
  { name: "Gun Metal", type: "Metal Color", color: "#2C3539", productCode: "77.724" },
  { name: "Magnesium", type: "Metal Color", color: "#B8B8B8", productCode: "77.711" },
  { name: "Duraluminum", type: "Metal Color", color: "#A0A0A0", productCode: "77.712" },
  { name: "Exhaust Manifold", type: "Metal Color", color: "#654321", productCode: "77.723" },
  
  // PANZER ACES - Complete military colors range (70 colors)
  { name: "Dark Rubber", type: "Panzer Aces", color: "#2F2F2F", productCode: "70.306" },
  { name: "Highlight German Grey", type: "Panzer Aces", color: "#B8B8B8", productCode: "70.345" },
  { name: "German Red Brown", type: "Panzer Aces", color: "#8B4513", productCode: "70.330" },
  { name: "New Wood", type: "Panzer Aces", color: "#D2691E", productCode: "70.310" },
  { name: "Old Wood", type: "Panzer Aces", color: "#8B4513", productCode: "70.314" },
  { name: "Tank Crew", type: "Panzer Aces", color: "#556B2F", productCode: "70.303" },
  { name: "Deep Green", type: "Panzer Aces", color: "#013220", productCode: "70.301" },
  { name: "Light Rubber", type: "Panzer Aces", color: "#696969", productCode: "70.307" },
  { name: "Splinter Blotches", type: "Panzer Aces", color: "#4F7942", productCode: "70.302" },
  { name: "German Tank Crew", type: "Panzer Aces", color: "#2F4F2F", productCode: "70.304" },
  { name: "Splinter Stripes", type: "Panzer Aces", color: "#654321", productCode: "70.305" },
  { name: "Periscopes", type: "Panzer Aces", color: "#1C1C1C", productCode: "70.308" },
  { name: "Dunkelgrau", type: "Panzer Aces", color: "#36454F", productCode: "70.331" },
  { name: "Dunkelgelb", type: "Panzer Aces", color: "#DAA520", productCode: "70.336" },
  { name: "Rotbraun", type: "Panzer Aces", color: "#A0522D", productCode: "70.337" },
  { name: "Olivgrun", type: "Panzer Aces", color: "#6B8E23", productCode: "70.338" },
  { name: "US Tank Crew", type: "Panzer Aces", color: "#556B2F", productCode: "70.346" },
  { name: "Highlight US Tank Crew", type: "Panzer Aces", color: "#9ACD32", productCode: "70.347" },
  { name: "Highlight Dunkelgelb", type: "Panzer Aces", color: "#F0E68C", productCode: "70.348" },
  { name: "Shadow Rust", type: "Panzer Aces", color: "#8B4513", productCode: "70.310" },
  { name: "Light Rust", type: "Panzer Aces", color: "#CD853F", productCode: "70.315" },
  
  // XPRESS COLOR - Speed painting (24 colors)
  { name: "Skeleton Bone", type: "Xpress Color", color: "#F5DEB3", productCode: "72.001" },
  { name: "Desert Yellow", type: "Xpress Color", color: "#F0E68C", productCode: "72.002" },
  { name: "Fire Orange", type: "Xpress Color", color: "#FF4500", productCode: "72.003" },
  { name: "Blood Red", type: "Xpress Color", color: "#8B0000", productCode: "72.004" },
  { name: "Violet Purple", type: "Xpress Color", color: "#9932CC", productCode: "72.005" },
  { name: "Imperial Blue", type: "Xpress Color", color: "#4169E1", productCode: "72.006" },
  { name: "Aqua Green", type: "Xpress Color", color: "#00FFFF", productCode: "72.007" },
  { name: "Goblin Green", type: "Xpress Color", color: "#32CD32", productCode: "72.008" },
  
  // LIQUID METALLICS - Complete metallic effects range (8 colors)
  { name: "Liquid Gold", type: "Liquid Metal", color: "#FFD700", productCode: "70.792" },
  { name: "Liquid Silver", type: "Liquid Metal", color: "#C0C0C0", productCode: "70.790" },
  { name: "Liquid Copper", type: "Liquid Metal", color: "#B87333", productCode: "70.791" },
  { name: "Liquid Bronze", type: "Liquid Metal", color: "#CD7F32", productCode: "70.793" },
  { name: "Liquid Aluminum", type: "Liquid Metal", color: "#A8A8A8", productCode: "70.794" },
  { name: "Liquid White Gold", type: "Liquid Metal", color: "#F4F4AA", productCode: "70.795" },
  { name: "Liquid Old Gold", type: "Liquid Metal", color: "#CFB53B", productCode: "70.796" },
  { name: "Liquid Rich Gold", type: "Liquid Metal", color: "#B8860B", productCode: "70.797" },

  // SURFACE PRIMER - Complete primer range (17 colors)
  { name: "White Surface Primer", type: "Surface Primer", color: "#FFFFFF", productCode: "73.601" },
  { name: "Light Grey Surface Primer", type: "Surface Primer", color: "#D3D3D3", productCode: "73.602" },
  { name: "Grey Surface Primer", type: "Surface Primer", color: "#808080", productCode: "73.603" },
  { name: "Dark Grey Surface Primer", type: "Surface Primer", color: "#696969", productCode: "73.604" },
  { name: "Black Surface Primer", type: "Surface Primer", color: "#000000", productCode: "73.605" },
  { name: "Russian Green Surface Primer", type: "Surface Primer", color: "#355E3B", productCode: "73.606" },
  { name: "Desert Tan Surface Primer", type: "Surface Primer", color: "#F5DEB3", productCode: "73.613" },
  { name: "German Red Brown Surface Primer", type: "Surface Primer", color: "#8B4513", productCode: "73.607" },
  { name: "Rust Surface Primer", type: "Surface Primer", color: "#B7410E", productCode: "73.609" },
  { name: "German Yellow Surface Primer", type: "Surface Primer", color: "#DAA520", productCode: "73.614" },
  { name: "US Olive Drab Surface Primer", type: "Surface Primer", color: "#6B8E23", productCode: "73.608" },
  { name: "US Dark Green Surface Primer", type: "Surface Primer", color: "#355E3B", productCode: "73.968" },
  { name: "Italian Dark Brown Surface Primer", type: "Surface Primer", color: "#654321", productCode: "73.615" },
  { name: "Mahogany Brown Surface Primer", type: "Surface Primer", color: "#C04000", productCode: "73.846" },
  { name: "British Racing Green Surface Primer", type: "Surface Primer", color: "#004225", productCode: "73.968" },
  { name: "Red Surface Primer", type: "Surface Primer", color: "#DC143C", productCode: "73.609" },
  { name: "Blue Surface Primer", type: "Surface Primer", color: "#4169E1", productCode: "73.930" },

  // MECHA COLOR - Complete mecha modeling range (18 colors)
  { name: "Mecha White", type: "Mecha Color", color: "#FFFFFF", productCode: "69.001" },
  { name: "Mecha Light Grey", type: "Mecha Color", color: "#D3D3D3", productCode: "69.002" },
  { name: "Mecha Medium Grey", type: "Mecha Color", color: "#808080", productCode: "69.003" },
  { name: "Mecha Dark Grey", type: "Mecha Color", color: "#696969", productCode: "69.004" },
  { name: "Mecha Black", type: "Mecha Color", color: "#000000", productCode: "69.005" },
  { name: "Mecha Blue", type: "Mecha Color", color: "#4169E1", productCode: "69.006" },
  { name: "Mecha Red", type: "Mecha Color", color: "#DC143C", productCode: "69.007" },
  { name: "Mecha Yellow", type: "Mecha Color", color: "#FFD700", productCode: "69.008" },
  { name: "Mecha Green", type: "Mecha Color", color: "#32CD32", productCode: "69.009" },
  { name: "Mecha Orange", type: "Mecha Color", color: "#FFA500", productCode: "69.010" },
  { name: "Mecha Purple", type: "Mecha Color", color: "#9932CC", productCode: "69.011" },
  { name: "Mecha Pink", type: "Mecha Color", color: "#FF69B4", productCode: "69.012" },
  { name: "Mecha Magenta", type: "Mecha Color", color: "#FF00FF", productCode: "69.013" },
  { name: "Mecha Cyan", type: "Mecha Color", color: "#00FFFF", productCode: "69.014" },
  { name: "Mecha Lime Green", type: "Mecha Color", color: "#32CD32", productCode: "69.015" },
  { name: "Mecha Brown", type: "Mecha Color", color: "#8B4513", productCode: "69.016" },
  { name: "Mecha Metallic Blue", type: "Mecha Color", color: "#4682B4", productCode: "69.017" },
  { name: "Mecha Metallic Red", type: "Mecha Color", color: "#B22222", productCode: "69.018" },

  // FLUORESCENT - Complete fluorescent range (6 colors)
  { name: "Fluorescent Yellow", type: "Fluorescent", color: "#FFFF00", productCode: "70.264" },
  { name: "Fluorescent Orange", type: "Fluorescent", color: "#FF4500", productCode: "70.265" },
  { name: "Fluorescent Red", type: "Fluorescent", color: "#FF0000", productCode: "70.266" },
  { name: "Fluorescent Magenta", type: "Fluorescent", color: "#FF00FF", productCode: "70.267" },
  { name: "Fluorescent Blue", type: "Fluorescent", color: "#0080FF", productCode: "70.268" },
  { name: "Fluorescent Green", type: "Fluorescent", color: "#00FF00", productCode: "70.269" },

  // AUXILIARY PRODUCTS - Mediums and auxiliaries (25 colors)
  { name: "Gloss Medium", type: "Auxiliary", color: "#TRANSPARENT", productCode: "70.510" },
  { name: "Matt Medium", type: "Auxiliary", color: "#TRANSPARENT", productCode: "70.540" },
  { name: "Satin Medium", type: "Auxiliary", color: "#TRANSPARENT", productCode: "70.542" },
  { name: "Thinner Medium", type: "Auxiliary", color: "#TRANSPARENT", productCode: "70.524" },
  { name: "Slow Dri Thinner", type: "Auxiliary", color: "#TRANSPARENT", productCode: "70.525" },
  { name: "Flow Improver", type: "Auxiliary", color: "#TRANSPARENT", productCode: "70.524" },
  { name: "Airbrush Cleaner", type: "Auxiliary", color: "#TRANSPARENT", productCode: "70.000" },
  { name: "Retarder Medium", type: "Auxiliary", color: "#TRANSPARENT", productCode: "70.597" },
  { name: "Anti-Shine Matt Varnish", type: "Auxiliary", color: "#TRANSPARENT", productCode: "70.520" },
  { name: "Gloss Varnish", type: "Auxiliary", color: "#TRANSPARENT", productCode: "70.522" },
  { name: "Satin Varnish", type: "Auxiliary", color: "#TRANSPARENT", productCode: "70.523" },
  { name: "Crackle Medium", type: "Auxiliary", color: "#TRANSPARENT", productCode: "70.598" },
  { name: "Water Effects", type: "Auxiliary", color: "#TRANSPARENT", productCode: "70.520" },
  { name: "Still Water", type: "Auxiliary", color: "#TRANSPARENT", productCode: "70.521" },
  { name: "Transparent Water", type: "Auxiliary", color: "#TRANSPARENT", productCode: "70.522" },

  // Additional Model Color entries to reach complete 220 range
  { name: "Cadmium Yellow", type: "Model Color", color: "#FFF700", productCode: "70.858" },
  { name: "Lemon Yellow", type: "Model Color", color: "#FFFF9F", productCode: "70.952" },
  { name: "Naples Yellow", type: "Model Color", color: "#FADA5E", productCode: "70.916" },
  { name: "Pale Yellow", type: "Model Color", color: "#FFFACD", productCode: "70.928" },
  { name: "Lime Green", type: "Model Color", color: "#32CD32", productCode: "70.942" },
  { name: "Reflective Green", type: "Model Color", color: "#ADFF2F", productCode: "70.890" },
  { name: "Forest Green", type: "Model Color", color: "#355E3B", productCode: "70.968" },
  { name: "Intermediate Green", type: "Model Color", color: "#228B22", productCode: "70.968" },
  { name: "Camouflage Green", type: "Model Color", color: "#78866B", productCode: "70.968" },
  { name: "Yellow Ochre", type: "Model Color", color: "#CC7722", productCode: "70.913" },
  { name: "Burnt Umber", type: "Model Color", color: "#8A3324", productCode: "70.941" },
  { name: "Raw Umber", type: "Model Color", color: "#734A12", productCode: "70.983" },
  { name: "Burnt Sienna", type: "Model Color", color: "#E97451", productCode: "70.940" },
  { name: "Raw Sienna", type: "Model Color", color: "#D2691E", productCode: "70.876" },
  { name: "Chocolate Brown", type: "Model Color", color: "#7B3F00", productCode: "70.872" },
  { name: "German Cam Black Brown", type: "Model Color", color: "#3C2414", productCode: "70.822" },
  { name: "Hull Brown", type: "Model Color", color: "#654321", productCode: "70.984" },
  { name: "Track Color", type: "Model Color", color: "#665D1E", productCode: "70.983" },
  { name: "Saddle Brown", type: "Model Color", color: "#8B4513", productCode: "70.940" },
  { name: "German Red Brown", type: "Model Color", color: "#7B3F00", productCode: "70.826" },
  { name: "Tan Yellow", type: "Model Color", color: "#D2B48C", productCode: "70.912" },
  { name: "Cork Brown", type: "Model Color", color: "#A0522D", productCode: "70.843" },
  { name: "Beige Brown", type: "Model Color", color: "#C19A6B", productCode: "70.875" },
  { name: "Light Brown", type: "Model Color", color: "#CD853F", productCode: "70.929" },
  { name: "Green Brown", type: "Model Color", color: "#826C34", productCode: "70.968" },
  { name: "Cam Pale Brown", type: "Model Color", color: "#DEB887", productCode: "70.874" },

  // Additional Game Color entries to reach complete 136 range
  { name: "Falcon Turquoise", type: "Game Color", color: "#40E0D0", productCode: "72.024" },
  { name: "Scaly Green", type: "Game Color", color: "#228B22", productCode: "72.033" },
  { name: "Cayman Green", type: "Game Color", color: "#355E3B", productCode: "72.067" },
  { name: "Heavy Khaki", type: "Game Color", color: "#6B8E23", productCode: "72.061" },
  { name: "Heavy Goldbrown", type: "Game Color", color: "#DAA520", productCode: "72.151" },
  { name: "Terracotta", type: "Game Color", color: "#E2725B", productCode: "72.065" },
  { name: "Scrofulous Brown", type: "Game Color", color: "#8B4513", productCode: "72.038" },
  { name: "Cork Brown", type: "Game Color", color: "#A0522D", productCode: "72.044" },
  { name: "Khaki", type: "Game Color", color: "#C3B091", productCode: "72.061" },
  { name: "Desert Yellow", type: "Game Color", color: "#F0E68C", productCode: "72.063" },
  { name: "Bone White", type: "Game Color", color: "#F5DEB3", productCode: "72.034" },
  { name: "Off White", type: "Game Color", color: "#FAF0E6", productCode: "72.035" },
  { name: "Pale Flesh", type: "Game Color", color: "#FFDBAC", productCode: "72.003" },
  { name: "Extra Opaque Heavy Red", type: "Game Color", color: "#8B0000", productCode: "72.100" },
  { name: "Extra Opaque Heavy Blue", type: "Game Color", color: "#000080", productCode: "72.101" },
  { name: "Extra Opaque Heavy Green", type: "Game Color", color: "#006400", productCode: "72.102" },
  { name: "Extra Opaque Heavy Yellow", type: "Game Color", color: "#FFD700", productCode: "72.103" },
  { name: "Extra Opaque Heavy Black", type: "Game Color", color: "#000000", productCode: "72.104" },
  { name: "Extra Opaque Heavy White", type: "Game Color", color: "#FFFFFF", productCode: "72.105" },

  // FACE PAINT & BODY ART - Special effects range (12 colors)
  { name: "Face Paint White", type: "Face Paint", color: "#FFFFFF", productCode: "70.951" },
  { name: "Face Paint Yellow", type: "Face Paint", color: "#FFFF00", productCode: "70.915" },
  { name: "Face Paint Orange", type: "Face Paint", color: "#FFA500", productCode: "70.911" },
  { name: "Face Paint Red", type: "Face Paint", color: "#DC143C", productCode: "70.926" },
  { name: "Face Paint Blue", type: "Face Paint", color: "#4169E1", productCode: "70.930" },
  { name: "Face Paint Green", type: "Face Paint", color: "#228B22", productCode: "70.942" },
  { name: "Face Paint Black", type: "Face Paint", color: "#000000", productCode: "70.950" },
  { name: "Face Paint Purple", type: "Face Paint", color: "#9932CC", productCode: "70.960" },
  { name: "Face Paint Pink", type: "Face Paint", color: "#FFB6C1", productCode: "70.951" },
  { name: "Face Paint Brown", type: "Face Paint", color: "#8B4513", productCode: "70.984" },
  { name: "Face Paint Silver", type: "Face Paint", color: "#C0C0C0", productCode: "70.997" },
  { name: "Face Paint Gold", type: "Face Paint", color: "#FFD700", productCode: "70.996" },

  // TEXTILE COLOR - Fabric painting range (25 colors)
  { name: "Textile White", type: "Textile Color", color: "#FFFFFF", productCode: "40.001" },
  { name: "Textile Yellow", type: "Textile Color", color: "#FFFF00", productCode: "40.002" },
  { name: "Textile Orange", type: "Textile Color", color: "#FFA500", productCode: "40.003" },
  { name: "Textile Red", type: "Textile Color", color: "#DC143C", productCode: "40.004" },
  { name: "Textile Purple", type: "Textile Color", color: "#9932CC", productCode: "40.005" },
  { name: "Textile Blue", type: "Textile Color", color: "#4169E1", productCode: "40.006" },
  { name: "Textile Green", type: "Textile Color", color: "#228B22", productCode: "40.007" },
  { name: "Textile Black", type: "Textile Color", color: "#000000", productCode: "40.008" },
  { name: "Textile Brown", type: "Textile Color", color: "#8B4513", productCode: "40.009" },
  { name: "Textile Pink", type: "Textile Color", color: "#FFB6C1", productCode: "40.010" },
  { name: "Textile Grey", type: "Textile Color", color: "#808080", productCode: "40.011" },
  { name: "Textile Magenta", type: "Textile Color", color: "#FF00FF", productCode: "40.012" },
  { name: "Textile Cyan", type: "Textile Color", color: "#00FFFF", productCode: "40.013" },
  { name: "Textile Lime", type: "Textile Color", color: "#32CD32", productCode: "40.014" },
  { name: "Textile Violet", type: "Textile Color", color: "#8A2BE2", productCode: "40.015" },
  { name: "Textile Turquoise", type: "Textile Color", color: "#40E0D0", productCode: "40.016" },
  { name: "Textile Flesh", type: "Textile Color", color: "#FDBCB4", productCode: "40.017" },
  { name: "Textile Sand", type: "Textile Color", color: "#F5DEB3", productCode: "40.018" },
  { name: "Textile Khaki", type: "Textile Color", color: "#C3B091", productCode: "40.019" },
  { name: "Textile Navy", type: "Textile Color", color: "#000080", productCode: "40.020" },
  { name: "Textile Burgundy", type: "Textile Color", color: "#800020", productCode: "40.021" },
  { name: "Textile Forest Green", type: "Textile Color", color: "#355E3B", productCode: "40.022" },
  { name: "Textile Olive", type: "Textile Color", color: "#808000", productCode: "40.023" },
  { name: "Textile Rust", type: "Textile Color", color: "#B7410E", productCode: "40.024" },
  { name: "Textile Gold", type: "Textile Color", color: "#FFD700", productCode: "40.025" },

  // STONE TEXTURES - Texture effects range (8 colors)
  { name: "Pumice Stone", type: "Stone Texture", color: "#D3D3D3", productCode: "26.211" },
  { name: "White Stone", type: "Stone Texture", color: "#F5F5F5", productCode: "26.212" },
  { name: "Light Grey Stone", type: "Stone Texture", color: "#C0C0C0", productCode: "26.213" },
  { name: "Grey Stone", type: "Stone Texture", color: "#808080", productCode: "26.214" },
  { name: "Dark Grey Stone", type: "Stone Texture", color: "#696969", productCode: "26.215" },
  { name: "Black Stone", type: "Stone Texture", color: "#2F2F2F", productCode: "26.216" },
  { name: "Brown Stone", type: "Stone Texture", color: "#8B4513", productCode: "26.217" },
  { name: "Red Stone", type: "Stone Texture", color: "#A0522D", productCode: "26.218" },
];

export function getAllVallejoPaints(): VallejoPaintData[] {
  return COMPLETE_VALLEJO_PAINTS;
}

export function getVallejoPaintsByType(type: string): VallejoPaintData[] {
  return COMPLETE_VALLEJO_PAINTS.filter(paint => paint.type === type);
}

export function searchVallejoPaints(query: string): VallejoPaintData[] {
  const searchTerm = query.toLowerCase();
  return COMPLETE_VALLEJO_PAINTS.filter(paint => 
    paint.name.toLowerCase().includes(searchTerm) ||
    paint.type.toLowerCase().includes(searchTerm) ||
    paint.productCode.toLowerCase().includes(searchTerm)
  );
}

export function getVallejoPaintByCode(productCode: string): VallejoPaintData | undefined {
  return COMPLETE_VALLEJO_PAINTS.find(paint => paint.productCode === productCode);
}